#! /usr/bin/env dart
/* Copyright (C) S. Brett Sutton - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Brett Sutton <bsutton@onepub.dev>, Jan 2022
 */

import 'dart:io';

/// dcli script generated by:
/// dcli create editor.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main() async {
  //'vi'.run;

  await Process.run('vi', []).then((result) {
    stdout.write(result.stdout);
    stderr.write(result.stderr);
  });
}
