#! /usr/bin/env dcli

import 'dart:io';

/// dcli script generated by:
/// dcli create editor.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main() {
  //'vi'.run;

  Process.run('vi', []).then((result) {
    stdout.write(result.stdout);
    stderr.write(result.stderr);
  });
}
