#! /usr/bin/env dshell

import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create compile_all.dart
/// 
/// See 
/// https://pub.dev/packages/dshell#-installing-tab-
/// 
/// For details on installing dshell.
/// 

void main() {

	find('*.dart', recursive: false).forEach((file) {
		'dshell compile -i $file'.run;
	});
}
