#! /usr/bin/env dshell

import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create dnsflush.dart
/// 
/// See 
/// https://pub.dev/packages/dshell#-installing-tab-
/// 
/// For details on installing dshell.
/// 

void main() {
	'sudo systemd-resolve --flush-caches'.run;
	'sudo systemd-resolve --statistics'.run;
}
