#! /usr/bin/env dcli

import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create dnsflush.dart
/// 
/// See 
/// https://pub.dev/packages/dcli#-installing-tab-
/// 
/// For details on installing dcli.
/// 

void main() {
	'sudo systemd-resolve --flush-caches'.run;
	'sudo systemd-resolve --statistics'.run;
}
