#! /usr/bin/env dcli

import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create dvirtualbox.dart
/// 
/// See 
/// https://pub.dev/packages/dcli#-installing-tab-
/// 
/// For details on installing dcli.
/// 

void main() {
  'sudo modprobe vboxdrv'.run;
  'virtualbox'.start(detached: true);
}
