#! /usr/bin/env dshell

import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create find_old_dart_packages.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///

void main() {
  find('build.gradle', recursive: true).forEach((file) {
    print('$file');
    read(file).forEach((line) {
      if (line.contains('compilesdkversion') && line.contains('27')) {
        print('file: $file, line: $line');
      }
    });
  });
}
