#! /usr/bin/env dshell

/// dshell script generated by:
/// dshell create future_test.dart
///
/// See
/// https://pub.dev/packages/dshell#-installing-tab-
///
/// For details on installing dshell.
///
import 'dart:async';

void main() {
  Future<void> doMe = doFutures();
  print('doFutures returned');
  doMe.then((_) => print('do Future completed'));
}

Future<void> doFutures() async {
  Completer done = Completer<void>();
  print('doFutures: started');
  Future.delayed(Duration(seconds: 10), () {
    print('delayed 10');
    done.complete();
  });
  Future.delayed(Duration(seconds: 5), () => print('delayed 5'));
  print('about to await');
  await Future.delayed(Duration(seconds: 7), () => print('delayed 7'));
  print('await finished');
  

  print('doFutures: ended');

  return done.future;
}
