#! /usr/bin/env dshell

import 'dart:io';
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create ipaddr.dart
/// 
/// See 
/// https://pub.dev/packages/dshell#-installing-tab-
/// 
/// For details on installing dshell.
/// 

void main() {

	NetworkInterface.list(includeLoopback: false, type: InternetAddressType.any)
    	.then((List<NetworkInterface> interfaces) {
        interfaces.forEach((interface) {
          print("name: ${interface.name}");
          int i = 0;
          interface.addresses.forEach((address) {
            print('  ${i++}) ${address.address}');
          });
        });
    });
}
