#! /usr/bin/env dcli

import 'dart:io';

/// dcli script generated by:
/// dcli create ipaddr.dart
/// 
/// See 
/// https://pub.dev/packages/dcli#-installing-tab-
/// 
/// For details on installing dcli.
/// 

void main() {

	NetworkInterface.list(includeLoopback: false, type: InternetAddressType.any)
    	.then((List<NetworkInterface> interfaces) {
        interfaces.forEach((interface) {
          print("name: ${interface.name}");
          var i = 0;
          interface.addresses.forEach((address) {
            print('  ${i++}) ${address.address}');
          });
        });
    });
}
