#! /home/bsutton/.pub-cache/bin/dshell

//##! /usr/bin/env dshell

import 'dart:io';
import 'package:dshell/dshell.dart';

/// dshell script generated by:
/// dshell create show_shell.dart
/// 
/// See 
/// https://pub.dev/packages/dshell#-installing-tab-
/// 
/// For details on installing dshell.
///

void main() {
	//'ps -p 0 '.run;
	print('shell: ${Shell().getShellPID()} : ${Shell().getShellName()}');
	print('shell path: ${Shell().getShellStartScriptPath()}');

	int cpid =pid ;
	while(cpid != 0)
	{
		cpid = Shell().getParentPID(cpid);
		print('cpid: $cpid ${Shell().getPIDName(cpid)}');
	}


}
