#! /home/bsutton/.pub-cache/bin/dcli
//##! /usr/bin/env dcli

import 'dart:io';
import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create show_shell.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main() {
  print('PWD: $pwd');
  //'ps -p 0 '.run;
  var shell = Shell.current;

  print('shell: ${shell.pid} : ${shell.name}');
  print('shell path: ${shell.pathToStartScript}');

  int? cpid = pid;
  while (cpid != 0) {
    cpid = ProcessHelper().getParentPID(cpid);
    if (cpid == 0) {
      break;
    }
    print('cpid: $cpid ${ProcessHelper().getProcessName(cpid)}');
  }
}
